export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_CONSTRUCTOR = 'DELETE_CONSTRUCTOR';
export const RESET_CONSTRUCTOR = 'RESET_CONSTRUCTOR';
export const REORDER_CONSTRUCTOR = 'REORDER_CONSTRUCTOR';